### ISSUE TITLE
Can I translate this guide to French? 🇫🇷

### ISSUE THREAD

**Issue by Stylizit** [elsewhencode/project-guidelines#125]
Because why not :)

**Comment by vpanjganj** [comment]
Yeah , go ahead please 😁

**Comment by Elkantor** [comment]
Yeah, it's a great idea ! :) Even if for me it's not a problem, we need it for our "dear old developers" in France haha ;) 
Anyway, it's always a good idea to translate informations !

**Comment by nacimgoura** [comment]
Hello,
I can help translate it into French.

**Comment by hulyaa** [comment]
I can translate into French

**Comment by vpanjganj** [comment]
PRs are more than welcome :)

**Comment by berlininvestment** [comment]
Yes

**Comment by Bam92** [comment]
Hi!

I can see that most people longtime ago have requested to translate this repo into french, but none of them has made a PR. For that I'd like to work on. Is there someone working already on it?

**Comment by vpanjganj** [comment]
@bam92 no one is working on French translation. You’re more than welcome to do it

**Comment by Bam92** [comment]
I am working on, then.
