### ISSUE TITLE
Question: How to handle with disapproved PR(a feature they intend to release, but they don't need that feature anymore)?

### ISSUE THREAD

**Issue by hoangnam2261** [elsewhencode/project-guidelines#138]
Hi there,
I have a question about git flow(i am not sure about it's type of flow). Please help me answer this question. I really appreciate your time.

We  have a central repository with a branch called "feature-branch-A".
We have 4 peoples(include me) are working on that branch. So those people will fork that center repo (create their own public repo) and work on "feature-branch-A".

After some days, when i am done with my task(task 1), i pushed code to my own public repo and created a PR for merging to "feature-branch-A" on the central repo. But unfortunately my team lead disapproved my PR(we don't need that task 1 anymore) and force me working on other task(task 2) not related to the current task(task 1) (but both still in the "feature-branch-A").

In that situation, what is the best practices for handling my public own repo?
1. I will revert all my commits for task 1 on my public own repo. And continue working on task 2. But when i am done with task 2, i push code to my own public repo and create PR for it. But that PR will include all commits of task 1(new code commit and revert commit) although we don't see any code changes for task 1.
2. I will delete my public own repo and  re-fork again for working on task 2.

Thank you so much for reading my question.

**Comment by mrmarktyy** [comment]
IMO,
You can branch off from your forked repo's master branch (eg, called feature branch B) for task 2.
