### ISSUE TITLE
Can I translate this guideline to Spanish?

### ISSUE THREAD

**Issue by jarcodallo** [elsewhencode/project-guidelines#139]
I want to translate this guideline by forking a repo if you approve.

**Comment by fjsuarez** [comment]
Let me know if you need help.

**Comment by vpanjganj** [comment]
@jarcodallo @fjsuarez yes please

**Comment by d4nyll** [comment]
The repository has an [MIT License](https://github.com/elsewhencode/project-guidelines/blob/master/LICENSE), which grants you permission to "use, **copy**, **modify**, merge, publish, distribute, sublicense, and/or sell copies" of the code. So you don't need the maintainers' approval.
