### ISSUE TITLE
Why there is exclamation mark in .gitignore file vor vscode?

### ISSUE THREAD

**Issue by muhammedogz** [elsewhencode/project-guidelines#171]
There are exclamation marks in `.gitignore` file.

```### VisualStudioCode ###
.vscode/*
!.vscode/settings.json
!.vscode/tasks.json
!.vscode/launch.json
!.vscode/extensions.json
```

Why preffered like that?

**Comment by Krupa27** [comment]
Exclamation marks are used as exclusion markers. 
When you put an exclamation mark  in a .gitignore file, it tells git to include files that match that pattern instead of ignoring them

**Comment by carkod** [comment]
@Krupa27 I believe what @muhammedogz means is why are exclamation marks preferred over not including them in the `.gitignore` at all.
