### ISSUE TITLE
Changing stage-2 to stage-4, also promote babel env

### ISSUE THREAD

**Issue by vpanjganj** [elsewhencode/project-guidelines#88]

**Comment by spartanatreyu** [comment]
Stage 2 is much to fresh to rely on.

Look at what has happened with things like decorators (placed into typescript, then the spec changed), or `Object.observe()`.

Stage 4 basically means that it will be included into browser engines, so you can write code in it with confidence that you can remove the polyfills down the line without having to change anything else.
